### ISSUE TITLE
Opens in Sublime instead of browser

### ISSUE THREAD

**Issue by ericseandevlin** [magbicaleman/open-in-browser#27]
I right-click to open in browser normally, but instead it just opens the same file in Sublime.

**Comment by jadegong** [comment]
Chang the default application to open files with extension html to your browser instead of Sublime.

**Comment by justinchristensen66** [comment]
I got the same problem, where do I set that up?  I was looking around and couldn't find where to switch it.

**Comment by JohnMica** [comment]
same issue here. html are set to open with browser by default but still they are open from Atom in Sublime ... any ideas how to solve this ?

**Comment by einfallstoll** [comment]
Setting the default application for HTML-Files to something other than my editor is no option. The main problem is the package itself: It should be called "open-in-default-application" than "open-in-browser", because this is exactly what it does: Calling the `open` command with nothing more than the file path and therefore triggering the default application to open the file.

The package should either detect the default browser and specify it using `open -b [Bundle Identifier] [File]` or allow to set it manually.

**Comment by magbicaleman** [comment]
![image](https://cloud.githubusercontent.com/assets/735039/15968920/b4aa3d7e-2efb-11e6-862b-e6683e51cbe1.png)
